# Generated by Django 5.2.1 on 2025-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('conference', 'Conference'), ('festival', 'Festival'), ('theater', 'Theater'), ('sports', 'Sports'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
