FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY backend/ .

# --- ADD THESE NEW LINES ---
# Make sure entrypoint.sh is executable before running it
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
# ---------------------------

CMD gunicorn core.wsgi:application --bind 0.0.0.0:$PORT