# Generated by Django 5.2.1 on 2025-06-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_remove_payment_quantity'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.payment'),
        ),
    ]
