# Generated by Django 5.2.1 on 2025-06-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_payment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
    ]
